# Generated by Django 5.0.4 on 2024-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='word',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
