# Generated by Django 5.0.4 on 2024-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rename_content_paragraph_text_remove_word_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='words',
            field=models.ManyToManyField(to='rest.word'),
        ),
    ]
